更改了 CI 的 release 名和文件名
Xposed-Modules-Repo/nil.nadph.qnotified pull request #1
Opened 2021-08-21 04:44 UTC by H4M5TER

2021-08-24 17:02 UTC, qwq233 requested changes

2021-08-24 17:02 UTC, qwq233 commented on .github/workflows/ci.yml
> -      id: apk
？这个干嘛删 下面需要的

2021-08-26 10:30 UTC, H4M5TER commented on .github/workflows/ci.yml
> -      id: apk
补上了，忘记 tag name 也有用到这个
version code 是怎么算的，感觉有点长过头了，不如说长得很像时间戳，但是好像也对不太上

2021-08-26 11:38 UTC, qwq233 approved these changes

2021-08-26 11:40 UTC, merged

2021-08-26 18:31 UTC, H4M5TER commented
最近几个build都正常工作了:tada: